In [1]:
import pandas as pd
df = pd.read_excel("titanic3.xls")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [2]:
totalSurvived = len(df[df['survived']==1])

In [3]:
import numpy as np
df['hasfamily'] = np.where((df['sibsp']==0) & (df['parch']==0), 0,1)

In [4]:
hasFamily = len(df[df['hasfamily']==1] )

In [30]:
df['accomodation'] = np.where(df['cabin'].notnull(), 1, 0)
totalAccomodation =df['accomodation'].count()
totalFare = df['fare'].count()
avgFare=df['fare'].mean()
print(hasFamily)
print(avgFare)
print(totalAccomodation)
print(totalFare)

519
33.29547928134572
1309
1308

In [8]:
df.corr()

,pclass,survived,age,sibsp,parch,fare,body,hasfamily,accomodation
pclass,1.000000,-0.312469,-0.408106,0.060832,0.018322,-0.558629,-0.034642,-0.147393,-0.713857
survived,-0.312469,1.000000,-0.055513,-0.027825,0.082660,0.244265,NaN,0.201719,0.302250
age,-0.408106,-0.055513,1.000000,-0.243699,-0.150917,0.178739,0.058809,-0.128755,0.289740
sibsp,0.060832,-0.027825,-0.243699,1.000000,0.373587,0.160238,-0.099961,0.591077,-0.009064
parch,0.018322,0.082660,-0.150917,0.373587,1.000000,0.221539,0.051099,0.549022,0.036806
fare,-0.558629,0.244265,0.178739,0.160238,0.221539,1.000000,-0.043110,0.274895,0.507253
body,-0.034642,NaN,0.058809,-0.099961,0.051099,-0.043110,1.000000,0.002237,0.083796
hasfamily,-0.147393,0.201719,-0.128755,0.591077,0.549022,0.274895,0.002237,1.000000,0.175812
accomodation,-0.713857,0.302250,0.289740,-0.009064,0.036806,0.507253,0.083796,0.175812,1.000000

In [28]:
import statsmodels.formula.api as sm
result = sm.ols(formula='survived ~ hasfamily + accomodation', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               survived   R-squared:                       0.114
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     84.13
Date:                Fri, 02 Mar 2018   Prob (F-statistic):           4.28e-35
Time:                        20:36:47   Log-Likelihood:                -833.22
No. Observations:                1309   AIC:                             1672.
Df Residuals:                    1306   BIC:                             1688.
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.2494      0.017     14.614      0.000       0.216       0.283
hasfamily        0.1523      0.026      5.795      0.000       0.101       0.204
accomodation     0.3201      0.031     10.406      0.000       0.260       0.380
==============================================================================
Omnibus:                     1872.109   Durbin-Watson:                   1.814
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.401
Skew:                           0.482   Prob(JB):                     1.46e-30
Kurtosis:                       1.738   Cond. No.                         2.82
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [29]:
import statsmodels.formula.api as sm
result = sm.ols(formula='survived ~ fare + accomodation', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               survived   R-squared:                       0.102
Model:                            OLS   Adj. R-squared:                  0.101
Method:                 Least Squares   F-statistic:                     74.43
Date:                Fri, 02 Mar 2018   Prob (F-statistic):           2.46e-31
Time:                        20:37:16   Log-Likelihood:                -841.39
No. Observations:                1308   AIC:                             1689.
Df Residuals:                    1305   BIC:                             1704.
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.2810      0.015     18.154      0.000       0.251       0.311
fare             0.0012      0.000      4.029      0.000       0.001       0.002
accomodation     0.2789      0.035      7.881      0.000       0.209       0.348
==============================================================================
Omnibus:                     3851.860   Durbin-Watson:                   1.810
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              147.454
Skew:                           0.497   Prob(JB):                     9.57e-33
Kurtosis:                       1.690   Cond. No.                         172.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [25]:
survivied =  len(df[df['survived']==1])
cabin =len(df[df['cabin'].notnull()])
hasfamily = len(df[df['hasfamily']==1] )
aboveAvgFare=len(df[(df['fare']>avgFare)] )
cabinSurvived = len(df[(df['cabin'].notnull()) & (df['survived']==1)])
hasfamilySurvived = len(df[(df['hasfamily']==1) & (df['survived']==1)])
hasfamilySurvived = len(df[(df['hasfamily']==1) & (df['survived']==1)])

p_cabin_family = (cabinSurvived/survivied) * (hasfamilySurvived/survivied)
p_cabin_avgfare = (cabinSurvived/survivied) * (aboveAvgFare/survivied)

In [26]:
print(p_cabin_avgfare)
print(p_cabin_family)

0.234688
0.201492